input:
  testset_file: "../data/ca_wikiqa_test_processedv2.json"
  vectorstore_dir: "/gpfs/projects/bsc88/apps/marina/rag/complete_wiki/vs/normal/index-BAAI_bge-m3-2000-200-SentenceTransformersTokenTextSplitter"
  embeddings_model_dir: "/gpfs/projects/bsc88/hf-models/"
  embeddings_model: "BAAI/bge-m3"
  reranking_model: "BAAI/bge-reranker-v2-m3"
output:
  dir: "./test_results_evaluate_retrieval"
  experiment_name: "test_marenostrum_models"
params:
  number_of_chunks: [1]
  base_url: "https://ca.wikipedia.org/wiki/"
  verbose: False
  force_download: False
  max_evaluations: 2
  reranking: [True]
  ncores: 1
  PYDEVD_WARN_EVALUATION_TIMEOUT: 10
  PYDEVD_UNBLOCK_THREADS_TIMEOUT: 10