input:
  testset_file: "../data/ca_wikiqa_test_processedv2.json"
  vectorstore_repo_name: "langtech-dev/wikiqa_vs"
output:
  dir: "./test_results_evaluate_retrieval"
params:
  embeddings_model: "BAAI/bge-m3"
  number_of_chunks: 1
  base_url: "https://ca.wikipedia.org/wiki/"
  verbose: False
