input:
  testset_file: "../data/ca_wikiqa_test_processedv2.json"
  vectorstore_model: "langtech-dev/complete_wiki_vs"
  embeddings_model: "BAAI/bge-m3"
output:
  dir: "./test_results_evaluate_retrieval"
params:
  number_of_chunks: 1
  base_url: "https://ca.wikipedia.org/wiki/"
  verbose: False
  force_download: False