input:
  testset_file: "../data/ca_wikiqa_test_processedv2.json"
  vectorstore_dir: "/gpfs/projects/bsc88/apps/marina/rag/complete_wiki/vs/normal/index-BAAI_bge-m3-2000-200-SentenceTransformersTokenTextSplitter"
  embeddings_model_dir: "/gpfs/projects/bsc88/hf-models/"
  embeddings_model: "BAAI/bge-m3"
output:
  dir: "./test_results_evaluate_retrieval"
params:
  number_of_chunks: [1]
  base_url: "https://ca.wikipedia.org/wiki/"
  verbose: False
  force_download: False
  max_evaluations: 2
  reranking: [False]